services:
  db:
    image: postgres:17
    platform: linux/amd64
    ports:
      - ${POSTGRESQL_PORT}:5432
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRESQL_DATABASE}
      - POSTGRES_USER=${POSTGRESQL_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    networks:
      - docker-fastapi-base
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRESQL_USERNAME} -d ${POSTGRESQL_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_SERVER=db
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      - HOST=${HOST}
      - ENVIRONMENT=${ENVIRONMENT}
      - BACKEND_CORS_ORIGINS=${BACKEND_CORS_ORIGINS}
      - API_KEY=${API_KEY}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - docker-fastapi-base

volumes:
  db-data:

networks:
  docker-fastapi-base:
    driver: bridge
